export type {
  CloudProviderAdapter,
  ScanOutput,
  ScanOptions,
  DiscoveryProgress,
  ProgressCallback,
} from './provider-interface.js';

export {
  awsScanner,
  buildAwsScanSummary,
  computeRetryDelayMs,
  DEFAULT_AWS_RETRY_POLICY,
  DEFAULT_SCANNER_CONCURRENCY,
  DEFAULT_SCANNER_TIMEOUT_MS,
  MAX_SCANNER_CONCURRENCY,
  MAX_SCANNER_TIMEOUT_MS,
  MIN_SCANNER_CONCURRENCY,
  MIN_SCANNER_TIMEOUT_MS,
  isAwsThrottlingError,
  scanAwsRegion,
  transformToScanResult,
  createAwsClient,
  buildAwsClientConfig,
  createEfsClient,
  createRoute53Client,
  getAwsCommandOptions,
  resolveAwsCredentials,
  assumeAwsRole,
  buildAssumeRoleSessionName,
  DEFAULT_ASSUME_ROLE_SESSION_DURATION_SECONDS,
  resolveAwsSourceCredentials,
  getCallerIdentity,
  paginateAws,
  buildResource,
  processWithConcurrencyLimit,
  sleep,
  type AwsClientOptions,
  type AssumeAwsRoleOptions,
  type AwsRetryPolicy,
  type AwsServiceScannerOutput,
  type AwsServiceScanner,
  type AwsServiceScannerDefinition,
  type AwsServiceScannerCapture,
  type AwsScanSummary,
  type AwsRegionScanResult,
  type AwsServiceScanResult,
  type ScanAwsRegionOptions,
  type CallerIdentity,
  type Enricher,
  type EnrichmentResult,
  type MetadataEnrichmentContext,
  type MetadataEnrichmentCredentials,
  type MetadataEnrichmentRegions,
  type MetadataProvider,
  dynamoDbPitrEnricher,
  ec2AsgEnricher,
  elasticacheFailoverEnricher,
  s3ReplicationEnricher,
} from './aws/index.js';

export {
  AzureScanner,
  AzureScannerNotImplementedError,
  azureScanner,
  createAzureClients,
  createAzureCredential,
  type AzureClientFactoryOptions,
  type AzureClientSet,
} from './azure/index.js';
