export {
  NodeType,
  EdgeType,
  type Severity,
  type EdgeProvenance,
  type CriticalitySource,
  type InfraNodeAttrs,
  type InfraEdgeAttrs,
  type ScanResult,
  type ScanEdge,
  type ReconciliationReport,
  type IngestReport,
  type CloudAdapter,
  type SPOFReport,
  type RedundancyCheck,
  type RedundancyIssue,
  type RegionalRisk,
  type CircularDependency,
  type CascadeNode,
  type CascadeChain,
  type GraphAnalysisReport,
  type CriticalPath,
  type AutoDetectedRisk,
  type BIAMetrics,
  type WeakPoint,
  type FinancialImpact,
  type BIAProcessResult,
  type BIAReportResult,
  type SimulationScenario,
  type SimulationBusinessImpact,
  type BlastRadiusMetrics,
  type SimulationRecommendation,
  type SimulationPropagationEvent,
  type WarRoomImpactedNode,
  type WarRoomData,
  type WarRoomCostTimelinePoint,
  type WarRoomNodeCostBreakdown,
  type WarRoomFinancial,
  type SimulationResult,
  type RecoveryStrategy,
  type LandingZoneItem,
  type LandingZoneReport,
  type ScenarioTemplate,
  type DiscoveryResourceKind,
  type OpenPort,
  type DiscoveredResource,
  type DiscoveredFlow,
  type DiscoveryConnectorResult,
  type DiscoveryCloudCredentials,
  type DiscoveryCredentials,
  type ApiScanStatus,
  type SerializedGraphAnalysis,
  type ApiCreateScanResponse,
  type ApiScanSummary,
  type ApiListScansResult,
  type ApiScanData,
  type ApiValidationSummary,
  type ApiEvidenceListResponse,
  type ApiAddEvidenceInput,
  type ApiServiceSummary,
  type ApiServicesResponse,
  type ApiServiceDetailResponse,
  type ApiStoredDrPlan,
  type ApiGeneratePlanResult,
  type ApiDriftEvent,
  type ApiDriftEventsResponse,
  type EncryptedPayload,
} from './types/index.js';

export { type InfrastructureRepository } from './ports/infrastructure-repository.js';

export { type Logger } from './ports/logger.js';

export { type CloudServiceResolver } from './ports/cloud-service-resolver.js';

export { type ScanRecord, type ScanRepository } from './ports/scan-repository.js';

export {
  type CloudProviderAdapter,
  type ScanOutput,
  type ScanOptions,
  type DiscoveryProgress,
  type ProgressCallback,
  AzureScanner,
  awsScanner,
  buildAwsScanSummary,
  computeRetryDelayMs,
  DEFAULT_AWS_RETRY_POLICY,
  DEFAULT_SCANNER_CONCURRENCY,
  DEFAULT_SCANNER_TIMEOUT_MS,
  MAX_SCANNER_CONCURRENCY,
  MAX_SCANNER_TIMEOUT_MS,
  MIN_SCANNER_CONCURRENCY,
  MIN_SCANNER_TIMEOUT_MS,
  isAwsThrottlingError,
  scanAwsRegion,
  azureScanner,
  createAzureClients,
  type AzureClientFactoryOptions,
  type AzureClientSet,
  getCallerIdentity,
  getAwsCommandOptions,
  type CallerIdentity,
  buildAwsClientConfig,
  assumeAwsRole,
  buildAssumeRoleSessionName,
  DEFAULT_ASSUME_ROLE_SESSION_DURATION_SECONDS,
  createEfsClient,
  transformToScanResult,
  processWithConcurrencyLimit,
  sleep,
  resolveAwsSourceCredentials,
  type AssumeAwsRoleOptions,
  type AwsRetryPolicy,
  type AwsServiceScannerOutput,
  type AwsServiceScanner,
  type AwsServiceScannerDefinition,
  type AwsServiceScannerCapture,
  type AwsScanSummary,
  type AwsRegionScanResult,
  type AwsServiceScanResult,
  type ScanAwsRegionOptions,
  dynamoDbPitrEnricher,
  ec2AsgEnricher,
  elasticacheFailoverEnricher,
  s3ReplicationEnricher,
  type Enricher,
  type EnrichmentResult,
  type MetadataProvider,
} from './providers/index.js';

export {
  getStartupDemoPipelineInput,
  type DemoPipelineInput,
} from './demo/startup-demo.js';

export {
  type GraphInstance,
  cloneGraph,
  getDependencies,
  getDependents,
  getBlastRadius,
  getSubgraph,
  exportForVisualization,
  calculateCascade,
  getGraphStats,
  getCriticalPaths,
  isAnalyzableServiceNode,
  type BlastRadiusResult,
  type BlastEdge,
  calculateBlastRadius,
  type CriticalityClassification,
  classifyServiceCriticality,
  detectRisks,
  inferBestEffortEdges,
  inferDependencies,
  DEFAULT_GRAPH_OVERRIDES_PATH,
  GRAPH_OVERRIDES_VERSION,
  type GraphOverrides,
  type GraphEdgeOverride,
  type GraphCriticalityOverride,
  type ApplyGraphOverridesResult,
  type ApplyGraphOverridesWarning,
  GraphOverrideValidationError,
  loadGraphOverrides,
  parseGraphOverrides,
  validateGraphOverrides,
  renderGraphOverridesTemplate,
  applyGraphOverrides,
  buildEdgeKey,
  DEFAULT_RESOLVER,
  analyzeFullGraph,
  generateLandingZoneRecommendations,
  SCENARIO_TEMPLATES,
  applyScenario,
  getScenarioOptions,
  runSimulation,
  buildSimulationPropagation,
  type GenerateBiaOptions,
  generateBIA,
} from './graph/index.js';

export {
  type InfrastructureNode,
  type DriftSeverity,
  type DriftCategory,
  type DriftChange,
  type DriftReport,
  type DriftRule,
  type DetectDriftOptions,
  type AnalyzeDriftImpactOptions,
  DEFAULT_DRIFT_RULES,
  detectDrift,
  analyzeDriftImpact,
} from './drift/index.js';

export {
  type DRCategory,
  type Grade,
  type InfraNode,
  type ScoreBreakdown,
  type EvidenceMaturitySummary,
  type ValidationSeverity,
  type ValidationStatus,
  type ValidationEdge,
  type ValidationContext,
  type ValidationResult,
  type ValidationResultWithEvidence,
  type ValidationRule,
  type ValidationReport,
  type ValidationReportWithEvidence,
  type WeightedValidationResult,
  type WeightedValidationResultWithEvidence,
  allValidationRules,
  blastRadiusWeight,
  calculatePotentialTestVerifiedScore,
  calculateWeightedScore,
  runValidation,
  gradeForScore,
  formatValidationReport,
  summarizeEvidenceMaturity,
} from './validation/index.js';

export {
  type Criticality,
  type ContextualFinding,
  type DRCapability,
  type DetectionSource,
  type LoadedManualServices,
  type ManualServiceDefinition,
  type RemediationAction,
  type ResourceRole,
  type Service,
  type ServiceDetectionResult,
  type ServiceDetectionSummary,
  type ServiceFinding,
  type ServicePosture,
  type ServicePostureService,
  type ServiceRecommendationProjection,
  type ServiceResource,
  type ServiceScore,
  type ServiceScoringResult,
  type UnassignedServicePosture,
  DEFAULT_SERVICES_FILE_PATH,
  SERVICES_FILE_VERSION,
  buildServiceIndex,
  buildServicePosture,
  classifyResourceRole,
  cleanServiceName,
  deriveCriticality,
  extractPrefixCandidate,
  hasSharedAvailabilityPattern,
  normalizeEdgeType,
  readNameTag,
  resolveNodeTags,
  resolveTagValue,
  slugifyServiceId,
  detectServices,
  detectCloudFormationServices,
  detectTagServices,
  detectTopologyServices,
  contextualizeFindings,
  loadManualServices,
  mergeServices,
  parseManualServices,
  scoreServices,
  type BuildServicePostureInput,
} from './services/index.js';

export {
  type InfrastructureNode as DrpInfrastructureNode,
  type RecoveryStrategy as DrpRecoveryStrategy,
  type RecoveryStrategyType,
  type RecoveryActionType,
  type RecoveryValidation,
  type RecoveryAction,
  type ValidationTest,
  type RTOFactorSource,
  type RTOFactor,
  type RTOEstimate,
  type EffectiveRTO,
  type DRPComponent,
  type DRPService,
  type DRPlan,
  type DRPlanValidationIssue,
  type DRPlanValidationReport,
  type DeserializeDrPlanSuccess,
  type DeserializeDrPlanFailure,
  type DeserializeDrPlanResult,
  type DriftImpactRtoChange,
  type DriftImpact,
  type AnalyzeDrpImpactOptions,
  type DriftImpactAnalysis,
  type RunbookStep,
  type RunbookCommand,
  type RunbookVerification,
  type RunbookRollback,
  type ComponentRunbook,
  type DRPRunbook,
  type ExecutionRisk,
  type RunbookStrategyFn,
  type RunbookStrategyDefinition,
  type DrPlanFormat,
  type RunbookFormat,
  type BuildRTOEstimateInputOptions,
  type RecoveryObjectives,
  type RTOEstimateInput,
  type GenerateDrPlanOptions,
  determineRecoveryStrategy,
  inferRecoveryStrategy,
  generateRecoverySteps,
  buildRTOEstimateInput,
  estimateRecovery,
  estimateRecoveryObjectives,
  estimateComponentRto,
  estimateComponentRpo,
  estimateRTO,
  estimateRPO,
  parseDrpDuration,
  generateDrPlan,
  generateDRPlan,
  calculateInfrastructureHash,
  serializeDrPlanToJson,
  serializeDrPlanToYaml,
  serializeDRPlan,
  deserializeDrPlan,
  deserializeDRPlan,
  validateDrPlanShape,
  analyzeDrpImpact,
  registerRunbookStrategy,
  getRunbookStrategy,
  getRunbookStrategyDefinition,
  listRegisteredStrategies,
  listRegisteredStrategyDefinitions,
  generateRunbook,
  serializeRunbook,
  serializeRunbookToJson,
  serializeRunbookToYaml,
  formatDrPlanReport,
  validateDrPlan,
  validateDRPlan,
} from './drp/index.js';

export {
  DEFAULT_EVIDENCE_EXPIRATION_DAYS,
  EVIDENCE_CONFIDENCE,
  EVIDENCE_TYPES,
  FileEvidenceStore,
  applyEvidenceFreshness,
  checkFreshness,
  extractEvidence,
  mergeEvidenceIntoValidationReport,
  type Evidence,
  type EvidenceObservation,
  type EvidenceStore,
  type EvidenceSource,
  type EvidenceSubject,
  type EvidenceTestResult,
  type EvidenceType,
  type FreshnessResult,
} from './evidence/index.js';

export {
  type EncryptedPayload as StrongholdEncryptedPayload,
  EncryptionError,
  decrypt,
  encrypt,
  isEncryptedPayload,
} from './encryption/index.js';

export {
  redact,
  redactObject,
  type RedactionOptions,
} from './redaction/index.js';

export {
  generateRecommendations,
  selectTopRecommendations,
  classifyRecommendationRisk,
  type Recommendation,
  type RecommendationGenerationInput,
  type RecommendationRisk,
} from './recommendations/index.js';

export {
  FileAuditLogger,
  type AuditAction,
  type AuditEntry,
  type AuditIdentity,
  type AuditLogger,
} from './audit/index.js';

export {
  DEFAULT_STRONGHOLD_CONFIG_PATH,
  STRONGHOLD_CONFIG_VERSION,
  type StrongholdConfigDefaults,
  type StrongholdAccountConfig,
  type StrongholdConfig,
  type ResolvedStrongholdAccount,
  StrongholdConfigValidationError,
  loadStrongholdConfig,
  parseStrongholdConfig,
  validateStrongholdConfig,
} from './config/index.js';
