export {
  NodeType,
  EdgeType,
  type Severity,
  type InfraNodeAttrs,
  type InfraEdgeAttrs,
  type ScanResult,
  type ScanEdge,
  type ReconciliationReport,
  type IngestReport,
  type CloudAdapter,
  type SPOFReport,
  type RedundancyCheck,
  type RedundancyIssue,
  type RegionalRisk,
  type CircularDependency,
  type CascadeNode,
  type CascadeChain,
  type GraphAnalysisReport,
  type CriticalPath,
  type AutoDetectedRisk,
  type BIAMetrics,
  type WeakPoint,
  type FinancialImpact,
  type BIAProcessResult,
  type BIAReportResult,
  type SimulationScenario,
  type SimulationBusinessImpact,
  type BlastRadiusMetrics,
  type SimulationRecommendation,
  type SimulationPropagationEvent,
  type WarRoomImpactedNode,
  type WarRoomData,
  type WarRoomCostTimelinePoint,
  type WarRoomNodeCostBreakdown,
  type WarRoomFinancial,
  type SimulationResult,
  type RecoveryStrategy,
  type LandingZoneItem,
  type LandingZoneReport,
  type ScenarioTemplate,
  type DiscoveryResourceKind,
  type OpenPort,
  type DiscoveredResource,
  type DiscoveredFlow,
  type DiscoveryConnectorResult,
  type DiscoveryCloudCredentials,
  type DiscoveryCredentials,
  type ApiScanStatus,
  type SerializedGraphAnalysis,
  type ApiCreateScanResponse,
  type ApiScanSummary,
  type ApiListScansResult,
  type ApiScanData,
  type ApiValidationSummary,
  type ApiStoredDrPlan,
  type ApiGeneratePlanResult,
  type ApiDriftEvent,
  type ApiDriftEventsResponse,
  type EncryptedPayload,
} from './types/index.js';

export { type InfrastructureRepository } from './ports/infrastructure-repository.js';

export { type Logger } from './ports/logger.js';

export { type CloudServiceResolver } from './ports/cloud-service-resolver.js';

export { type ScanRecord, type ScanRepository } from './ports/scan-repository.js';

export {
  type CloudProviderAdapter,
  type ScanOutput,
  type ScanOptions,
  type DiscoveryProgress,
  type ProgressCallback,
  AzureScanner,
  awsScanner,
  scanAwsRegion,
  azureScanner,
  createAzureClients,
  type AzureClientFactoryOptions,
  type AzureClientSet,
  getCallerIdentity,
  type CallerIdentity,
  createEfsClient,
  transformToScanResult,
  dynamoDbPitrEnricher,
  ec2AsgEnricher,
  elasticacheFailoverEnricher,
  s3ReplicationEnricher,
  type Enricher,
  type EnrichmentResult,
  type MetadataProvider,
} from './providers/index.js';

export {
  getStartupDemoPipelineInput,
  type DemoPipelineInput,
} from './demo/startup-demo.js';

export {
  type GraphInstance,
  cloneGraph,
  getDependencies,
  getDependents,
  getBlastRadius,
  getSubgraph,
  exportForVisualization,
  calculateCascade,
  getGraphStats,
  getCriticalPaths,
  isAnalyzableServiceNode,
  type BlastRadiusResult,
  type BlastEdge,
  calculateBlastRadius,
  type CriticalityClassification,
  classifyServiceCriticality,
  detectRisks,
  inferBestEffortEdges,
  inferDependencies,
  DEFAULT_RESOLVER,
  analyzeFullGraph,
  generateLandingZoneRecommendations,
  SCENARIO_TEMPLATES,
  applyScenario,
  getScenarioOptions,
  runSimulation,
  buildSimulationPropagation,
  type GenerateBiaOptions,
  generateBIA,
} from './graph/index.js';

export {
  type InfrastructureNode,
  type DriftSeverity,
  type DriftCategory,
  type DriftChange,
  type DriftReport,
  type DriftRule,
  type DetectDriftOptions,
  type AnalyzeDriftImpactOptions,
  DEFAULT_DRIFT_RULES,
  detectDrift,
  analyzeDriftImpact,
} from './drift/index.js';

export {
  type DRCategory,
  type InfraNode,
  type ScoreBreakdown,
  type ValidationSeverity,
  type ValidationStatus,
  type ValidationEdge,
  type ValidationContext,
  type ValidationResult,
  type ValidationRule,
  type ValidationReport,
  type WeightedValidationResult,
  allValidationRules,
  blastRadiusWeight,
  runValidation,
  formatValidationReport,
} from './validation/index.js';

export {
  type InfrastructureNode as DrpInfrastructureNode,
  type RecoveryStrategy as DrpRecoveryStrategy,
  type RecoveryStrategyType,
  type RecoveryActionType,
  type RecoveryValidation,
  type RecoveryAction,
  type ValidationTest,
  type RTOFactorSource,
  type RTOFactor,
  type RTOEstimate,
  type EffectiveRTO,
  type DRPComponent,
  type DRPService,
  type DRPlan,
  type DRPlanValidationIssue,
  type DRPlanValidationReport,
  type DeserializeDrPlanSuccess,
  type DeserializeDrPlanFailure,
  type DeserializeDrPlanResult,
  type RunbookStep,
  type RunbookCommand,
  type RunbookVerification,
  type RunbookRollback,
  type ComponentRunbook,
  type DRPRunbook,
  type RunbookStrategyFn,
  type DrPlanFormat,
  type RunbookFormat,
  type BuildRTOEstimateInputOptions,
  type RecoveryObjectives,
  type RTOEstimateInput,
  type GenerateDrPlanOptions,
  determineRecoveryStrategy,
  inferRecoveryStrategy,
  generateRecoverySteps,
  buildRTOEstimateInput,
  estimateRecovery,
  estimateRecoveryObjectives,
  estimateComponentRto,
  estimateComponentRpo,
  estimateRTO,
  estimateRPO,
  parseDrpDuration,
  generateDrPlan,
  generateDRPlan,
  calculateInfrastructureHash,
  serializeDrPlanToJson,
  serializeDrPlanToYaml,
  serializeDRPlan,
  deserializeDrPlan,
  deserializeDRPlan,
  validateDrPlanShape,
  registerRunbookStrategy,
  getRunbookStrategy,
  listRegisteredStrategies,
  generateRunbook,
  serializeRunbook,
  serializeRunbookToJson,
  serializeRunbookToYaml,
  formatDrPlanReport,
  validateDrPlan,
  validateDRPlan,
} from './drp/index.js';

export {
  type EncryptedPayload as StrongholdEncryptedPayload,
  EncryptionError,
  decrypt,
  encrypt,
  isEncryptedPayload,
} from './encryption/index.js';

export {
  redact,
  redactObject,
  type RedactionOptions,
} from './redaction/index.js';

export {
  FileAuditLogger,
  type AuditAction,
  type AuditEntry,
  type AuditIdentity,
  type AuditLogger,
} from './audit/index.js';
