declare function extractTextFromPdf(filePath: string): Promise<string>;
declare function decodeXmlEntities(text: string): string;
declare function extractTextFromDocx(filePath: string): Promise<string>;
declare function extractTextFromPptx(filePath: string): Promise<string>;
export declare function ingestDocumentText(documentId: string, tenantId: string): Promise<{
    id: string;
    tenantId: string;
    createdAt: Date;
    updatedAt: Date;
    description: string | null;
    originalName: string;
    storedName: string;
    mimeType: string;
    size: number;
    storagePath: string;
    fileHash: string | null;
    docType: string | null;
    detectedDocType: string | null;
    detectedMetadata: string | null;
    textHash: string | null;
    vectorizedAt: Date | null;
    textExtractedAt: Date | null;
    ingestionStatus: string;
    ingestionQueuedAt: Date | null;
    ingestionError: string | null;
    retentionUntil: Date | null;
    embeddingRetentionUntil: Date | null;
    extractionStatus: string;
    extractionError: string | null;
    textContent: string | null;
}>;
export declare function enqueueDocumentIngestion(documentId: string, tenantId: string): Promise<{
    id: string;
    tenantId: string;
    createdAt: Date;
    updatedAt: Date;
    description: string | null;
    originalName: string;
    storedName: string;
    mimeType: string;
    size: number;
    storagePath: string;
    fileHash: string | null;
    docType: string | null;
    detectedDocType: string | null;
    detectedMetadata: string | null;
    textHash: string | null;
    vectorizedAt: Date | null;
    textExtractedAt: Date | null;
    ingestionStatus: string;
    ingestionQueuedAt: Date | null;
    ingestionError: string | null;
    retentionUntil: Date | null;
    embeddingRetentionUntil: Date | null;
    extractionStatus: string;
    extractionError: string | null;
    textContent: string | null;
}>;
export declare const __test__: {
    extractTextFromPdf: typeof extractTextFromPdf;
    extractTextFromDocx: typeof extractTextFromDocx;
    extractTextFromPptx: typeof extractTextFromPptx;
    decodeXmlEntities: typeof decodeXmlEntities;
};
export {};
//# sourceMappingURL=documentIngestionService.d.ts.map