// ============================================================
// Exercise Augmentation Service
// Enriches PRA/PCA exercises with simulation-driven data:
// - Auto-generate checklists from simulation results
// - Compare actual exercise outcomes vs. simulation predictions
// - Generate lessons learned
// ============================================================

import type { PrismaClient } from '@prisma/client';

export interface AutoGeneratedChecklist {
  items: Array<{
    order: number;
    title: string;
    description: string;
    role: string;
    blocking: boolean;
    category: 'preparation' | 'detection' | 'response' | 'recovery' | 'communication';
  }>;
}

export interface ExerciseComparison {
  predicted: {
    totalNodesAffected: number;
    percentageAffected: number;
    estimatedDowntimeMinutes: number;
    estimatedFinancialLoss: number;
    postIncidentScore: number;
    affectedServicesCount: number;
  };
  actual: {
    rtoObservedMinutes: number | null;
    status: string;
    completedAt: Date | null;
    startedAt: Date | null;
    notes: string | null;
  };
  deltas: {
    rtoActualVsPredicted: {
      predicted: number;
      actual: number | null;
      delta: number | null;
      assessment: string;
    };
  };
  lessonsLearned: string[];
}

/**
 * Auto-generates a checklist for an exercise based on simulation results.
 * The simulation predicts which nodes/services will be affected, so we
 * generate actionable steps for the exercise team.
 */
export async function generateChecklistFromSimulation(
  prisma: PrismaClient,
  simulationId: string,
  tenantId: string
): Promise<AutoGeneratedChecklist> {
  const simulation = await prisma.simulation.findFirst({
    where: { id: simulationId, tenantId },
  });

  if (!simulation) {
    throw new Error('Simulation not found');
  }

  const result = simulation.result as any;
  const scenarioType = simulation.scenarioType;
  const items: AutoGeneratedChecklist['items'] = [];
  let order = 1;

  // --- PREPARATION ---
  items.push({
    order: order++,
    title: 'Notify all participants',
    description: `Inform the exercise team that a ${scenarioType.replace(/_/g, ' ')} scenario will be tested.`,
    role: 'Exercise Coordinator',
    blocking: true,
    category: 'preparation',
  });

  items.push({
    order: order++,
    title: 'Verify monitoring dashboards',
    description: 'Ensure all monitoring and alerting systems are operational before starting.',
    role: 'Operations Team',
    blocking: true,
    category: 'preparation',
  });

  items.push({
    order: order++,
    title: 'Document initial system state',
    description: `Record current state: ${simulation.totalNodesAffected} nodes predicted to be affected.`,
    role: 'Operations Team',
    blocking: false,
    category: 'preparation',
  });

  // --- DETECTION ---
  items.push({
    order: order++,
    title: 'Inject failure scenario',
    description: `Simulate: ${simulation.name || scenarioType}. Expected impact: ${simulation.percentageAffected.toFixed(1)}% of infrastructure.`,
    role: 'Exercise Coordinator',
    blocking: true,
    category: 'detection',
  });

  items.push({
    order: order++,
    title: 'Verify alert triggering',
    description: 'Confirm that monitoring systems detect the simulated failure within expected timeframes.',
    role: 'Operations Team',
    blocking: true,
    category: 'detection',
  });

  items.push({
    order: order++,
    title: 'Record detection time',
    description: 'Log the time between failure injection and first alert. Compare with predicted detection time.',
    role: 'Exercise Observer',
    blocking: false,
    category: 'detection',
  });

  // --- RESPONSE ---
  const affectedNodes = result.affectedNodes || [];
  const businessImpact = result.businessImpact || [];

  if (businessImpact.length > 0) {
    items.push({
      order: order++,
      title: 'Activate incident response',
      description: `${businessImpact.length} business services predicted to be impacted. Activate incident response procedures.`,
      role: 'Incident Manager',
      blocking: true,
      category: 'response',
    });
  }

  items.push({
    order: order++,
    title: 'Assess actual impact scope',
    description: `Compare actual affected nodes with simulation prediction (${affectedNodes.length} nodes predicted).`,
    role: 'Operations Team',
    blocking: false,
    category: 'response',
  });

  items.push({
    order: order++,
    title: 'Communicate with stakeholders',
    description: 'Send status update to relevant business stakeholders about the exercise progress.',
    role: 'Communications Lead',
    blocking: false,
    category: 'communication',
  });

  // --- RECOVERY ---
  const recommendations = result.recommendations || [];
  for (const rec of recommendations.slice(0, 3)) {
    items.push({
      order: order++,
      title: `Execute recovery: ${rec.title || rec.action || 'Recovery step'}`,
      description: rec.description || `Priority: ${rec.priority || 'medium'}`,
      role: 'Recovery Team',
      blocking: true,
      category: 'recovery',
    });
  }

  items.push({
    order: order++,
    title: 'Verify service restoration',
    description: `Confirm all ${simulation.totalNodesAffected} affected nodes are restored. Target RTO: ${simulation.estimatedDowntime} minutes.`,
    role: 'Operations Team',
    blocking: true,
    category: 'recovery',
  });

  items.push({
    order: order++,
    title: 'Record actual recovery time',
    description: 'Log the total time from failure to full restoration. Compare with predicted RTO.',
    role: 'Exercise Observer',
    blocking: false,
    category: 'recovery',
  });

  // --- POST-EXERCISE ---
  items.push({
    order: order++,
    title: 'Conduct post-exercise debrief',
    description: 'Gather all participants for a debrief. Compare actual outcomes with simulation predictions.',
    role: 'Exercise Coordinator',
    blocking: false,
    category: 'communication',
  });

  items.push({
    order: order++,
    title: 'Document lessons learned',
    description: 'Record deviations from predictions and identify improvement opportunities.',
    role: 'Exercise Coordinator',
    blocking: false,
    category: 'communication',
  });

  return { items };
}

/**
 * Compares exercise results with simulation predictions.
 * Identifies deltas and generates lessons learned.
 */
export async function compareExerciseWithSimulation(
  prisma: PrismaClient,
  exerciseId: string,
  tenantId: string
): Promise<ExerciseComparison> {
  const exercise = await prisma.exercise.findFirst({
    where: { id: exerciseId, tenantId },
    include: {
      results: true,
      checklistItems: true,
    },
  });

  if (!exercise) {
    throw new Error('Exercise not found');
  }

  if (!exercise.resilienceSimulationId) {
    throw new Error('Exercise is not linked to a resilience simulation');
  }

  const simulation = await prisma.simulation.findFirst({
    where: { id: exercise.resilienceSimulationId, tenantId },
  });

  if (!simulation) {
    throw new Error('Linked simulation not found');
  }

  const result = simulation.result as any;
  const exerciseResult = exercise.results[0]; // Most recent result

  // Calculate actual RTO from exercise result
  let actualRtoMinutes: number | null = null;
  if (exerciseResult?.rtoObservedHours != null) {
    actualRtoMinutes = exerciseResult.rtoObservedHours * 60;
  } else if (exerciseResult?.startedAt && exerciseResult?.completedAt) {
    actualRtoMinutes = Math.round(
      (new Date(exerciseResult.completedAt).getTime() - new Date(exerciseResult.startedAt).getTime()) / 60000
    );
  }

  const predictedDowntime = simulation.estimatedDowntime;
  const rtoDelta = actualRtoMinutes != null ? actualRtoMinutes - predictedDowntime : null;

  let rtoAssessment: string;
  if (rtoDelta === null) {
    rtoAssessment = 'No actual RTO recorded. Ensure exercise results include timing data.';
  } else if (Math.abs(rtoDelta) <= predictedDowntime * 0.1) {
    rtoAssessment = 'Actual RTO closely matches prediction. Simulation model is well-calibrated.';
  } else if (rtoDelta > 0) {
    rtoAssessment = `Actual recovery was ${rtoDelta} minutes slower than predicted. Review recovery procedures for bottlenecks.`;
  } else {
    rtoAssessment = `Actual recovery was ${Math.abs(rtoDelta)} minutes faster than predicted. Consider updating simulation parameters.`;
  }

  // Generate lessons learned
  const lessons: string[] = [];

  if (rtoDelta !== null && rtoDelta > predictedDowntime * 0.2) {
    lessons.push('Recovery time significantly exceeded predictions. Consider investing in automation and runbook optimization.');
  }
  if (rtoDelta !== null && rtoDelta < -predictedDowntime * 0.2) {
    lessons.push('Recovery was faster than predicted. Update simulation models with more optimistic parameters.');
  }

  const completedChecklist = exercise.checklistItems.filter((c: any) => c.isCompleted);
  const checklistCompletion = exercise.checklistItems.length > 0
    ? (completedChecklist.length / exercise.checklistItems.length) * 100
    : 0;

  if (checklistCompletion < 80) {
    lessons.push(`Only ${checklistCompletion.toFixed(0)}% of checklist items were completed. Review exercise scope and team readiness.`);
  }

  if (exerciseResult?.status === 'FAILED') {
    lessons.push('Exercise was marked as FAILED. Investigate root causes and update recovery procedures.');
  }

  const businessImpact = result.businessImpact || [];
  if (businessImpact.length > 0) {
    lessons.push(`${businessImpact.length} business services were predicted to be impacted. Verify actual impact alignment and update BIA if needed.`);
  }

  if (lessons.length === 0) {
    lessons.push('Exercise completed within expected parameters. Continue regular testing cadence.');
  }

  return {
    predicted: {
      totalNodesAffected: simulation.totalNodesAffected,
      percentageAffected: simulation.percentageAffected,
      estimatedDowntimeMinutes: simulation.estimatedDowntime,
      estimatedFinancialLoss: simulation.estimatedFinancialLoss || 0,
      postIncidentScore: simulation.postIncidentScore,
      affectedServicesCount: businessImpact.length,
    },
    actual: {
      rtoObservedMinutes: actualRtoMinutes,
      status: exerciseResult?.status || 'unknown',
      completedAt: exerciseResult?.completedAt || null,
      startedAt: exerciseResult?.startedAt || null,
      notes: exerciseResult?.comments || null,
    },
    deltas: {
      rtoActualVsPredicted: {
        predicted: predictedDowntime,
        actual: actualRtoMinutes,
        delta: rtoDelta,
        assessment: rtoAssessment,
      },
    },
    lessonsLearned: lessons,
  };
}
