import { describe, expect, it } from 'vitest';

import { buildIamPolicy, renderIamPolicyTerraform } from '../config/iam-policy.js';
import { SUPPORTED_SERVICES } from '../config/options.js';

describe('iam-policy', () => {
  it('contains the expected statements', () => {
    const policy = buildIamPolicy();

    expect(policy.Statement).toHaveLength(16);
  });

  it('uses read-only List/Describe/Get actions only', () => {
    const policy = buildIamPolicy();
    const actions = policy.Statement.flatMap((statement) => statement.Action);

    expect(actions.every((action) => /:(Describe|List|Get)/.test(action))).toBe(true);
  });

  it('filters to selected services', () => {
    const policy = buildIamPolicy(['rds', 's3']);

    expect(policy.Statement.map((statement) => statement.Sid)).toEqual([
      'StrongholdReadOnlyRDS',
      'StrongholdReadOnlyS3',
      'StrongholdReadOnlySTS',
    ]);
  });

  it('does not use wildcard actions and terraform output includes provenance', () => {
    const policy = buildIamPolicy();
    const actions = policy.Statement.flatMap((statement) => statement.Action);

    expect(actions.includes('*')).toBe(false);
    expect(renderIamPolicyTerraform(policy)).toContain('Generated by stronghold-dr v0.1.0');
  });

  it('contains one statement per scanned service plus STS', () => {
    const policy = buildIamPolicy(SUPPORTED_SERVICES);

    expect(policy.Statement).toHaveLength(SUPPORTED_SERVICES.length + 1);
  });

  it('never includes mutating IAM actions and renders a Terraform policy resource', () => {
    const policy = buildIamPolicy();
    const actions = policy.Statement.flatMap((statement) => statement.Action);
    const terraform = renderIamPolicyTerraform(policy);

    expect(actions.some((action) => /:(Put|Create|Delete|Update)/.test(action))).toBe(false);
    expect(terraform).toContain('resource "aws_iam_policy" "stronghold_read_only"');
  });
});
